-- MySQL Script generated by MySQL Workbench
-- Wed Jan 25 22:22:21 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bread
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bread
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bread` DEFAULT CHARACTER SET utf8 ;
USE `bread` ;

-- -----------------------------------------------------
-- Table `bread`.`Warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bread`.`Warehouse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `capacity` DECIMAL NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idWarehouse_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bread`.`Crop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bread`.`Crop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Warehouse_id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `variety` VARCHAR(50) NOT NULL,
  `amount` DECIMAL NOT NULL,
  `grade` ENUM('Відмінно', 'Добре', 'Задовільно', 'Погано', 'Зіпсовано') NOT NULL DEFAULT 'Задовільно',
  `moisture` FLOAT NOT NULL,
  `temperature` FLOAT NOT NULL DEFAULT 20,
  PRIMARY KEY (`id`, `Warehouse_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Crop_Warehouse1_idx` (`Warehouse_id` ASC) VISIBLE,
  CONSTRAINT `fk_Crop_Warehouse1`
    FOREIGN KEY (`Warehouse_id`)
    REFERENCES `bread`.`Warehouse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bread`.`Standard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bread`.`Standard` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Crop_id` INT NOT NULL,
  `min_moisture` FLOAT NOT NULL,
  `max_moisture` FLOAT NOT NULL,
  `minor_risk` INT NOT NULL,
  `middle_rist` INT NOT NULL,
  `major_risk` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Standard_Crop1_idx` (`Crop_id` ASC) VISIBLE,
  CONSTRAINT `fk_Standard_Crop1`
    FOREIGN KEY (`Crop_id`)
    REFERENCES `bread`.`Crop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bread`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bread`.`Supplier` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `number` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bread`.`Consignment_IN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bread`.`Consignment_IN` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Supplier_id` INT NOT NULL,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Supply_Supplier_idx` (`Supplier_id` ASC) VISIBLE,
  CONSTRAINT `fk_Supply_Supplier`
    FOREIGN KEY (`Supplier_id`)
    REFERENCES `bread`.`Supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bread`.`Consignment_OUT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bread`.`Consignment_OUT` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Crop_id` INT NOT NULL,
  `amount` DECIMAL NOT NULL,
  `moisture` FLOAT NOT NULL,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `name` VARCHAR(50) NOT NULL,
  `number` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`, `Crop_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Consignment_OUT_Crop1_idx` (`Crop_id` ASC) VISIBLE,
  CONSTRAINT `fk_Consignment_OUT_Crop1`
    FOREIGN KEY (`Crop_id`)
    REFERENCES `bread`.`Crop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bread`.`Consignment_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bread`.`Consignment_data` (
  `Consignment_IN_id` INT NOT NULL,
  `Crop_id` INT NOT NULL,
  `amount` DECIMAL NOT NULL,
  `moisture` FLOAT NOT NULL,
  PRIMARY KEY (`Consignment_IN_id`, `Crop_id`),
  INDEX `fk_Consignment_IN_has_Crop_Crop1_idx` (`Crop_id` ASC) VISIBLE,
  INDEX `fk_Consignment_IN_has_Crop_Consignment_IN1_idx` (`Consignment_IN_id` ASC) VISIBLE,
  CONSTRAINT `fk_Consignment_IN_has_Crop_Consignment_IN1`
    FOREIGN KEY (`Consignment_IN_id`)
    REFERENCES `bread`.`Consignment_IN` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consignment_IN_has_Crop_Crop1`
    FOREIGN KEY (`Crop_id`)
    REFERENCES `bread`.`Crop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
