-- MySQL Script generated by MySQL Workbench
-- Tue Feb  7 17:19:30 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bread.loc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bread.loc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bread.loc` DEFAULT CHARACTER SET utf8 ;
USE `bread.loc` ;

-- -----------------------------------------------------
-- Table `bread.loc`.`Standard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bread.loc`.`Standard` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `minor_risk` INT NOT NULL DEFAULT 2,
  `major_risk` INT NOT NULL DEFAULT 12,
  `min_moisture` FLOAT NOT NULL,
  `max_moisture` FLOAT NOT NULL,
  `min_garbage` FLOAT NOT NULL,
  `max_garbage` FLOAT NOT NULL,
  `min_minerals` FLOAT NOT NULL,
  `max_minerals` FLOAT NOT NULL,
  `min_nature` FLOAT NOT NULL,
  `max_nature` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bread.loc`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bread.loc`.`Supplier` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `number` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bread.loc`.`Warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bread.loc`.`Warehouse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `capacity` DECIMAL NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idWarehouse_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bread.loc`.`Characteristic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bread.loc`.`Characteristic` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `moisture` FLOAT NOT NULL,
  `garbage` FLOAT NOT NULL,
  `minerals` FLOAT NOT NULL,
  `nature` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bread.loc`.`Crop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bread.loc`.`Crop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Supplier_id` INT NOT NULL,
  `Warehouse_id` INT NOT NULL,
  `Characteristic_id` INT NOT NULL,
  `Standard_id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `variety` VARCHAR(50) NOT NULL,
  `amount` DECIMAL NOT NULL,
  `grade` ENUM('Відмінно', 'Добре', 'Задовільно', 'Погано', 'Зіпсовано') NOT NULL DEFAULT 'Задовільно',
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `Supplier_id`, `Warehouse_id`, `Characteristic_id`, `Standard_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Crop_Warehouse1_idx` (`Warehouse_id` ASC) VISIBLE,
  INDEX `fk_Crop_Characteristic1_idx` (`Characteristic_id` ASC) VISIBLE,
  INDEX `fk_Crop_Supplier1_idx` (`Supplier_id` ASC) VISIBLE,
  INDEX `fk_Crop_Standard1_idx` (`Standard_id` ASC) VISIBLE,
  CONSTRAINT `fk_Crop_Warehouse1`
    FOREIGN KEY (`Warehouse_id`)
    REFERENCES `bread.loc`.`Warehouse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Crop_Characteristic1`
    FOREIGN KEY (`Characteristic_id`)
    REFERENCES `bread.loc`.`Characteristic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Crop_Supplier1`
    FOREIGN KEY (`Supplier_id`)
    REFERENCES `bread.loc`.`Supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Crop_Standard1`
    FOREIGN KEY (`Standard_id`)
    REFERENCES `bread.loc`.`Standard` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bread.loc`.`Consignment_OUT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bread.loc`.`Consignment_OUT` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Crop_id` INT NOT NULL,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `name` VARCHAR(50) NOT NULL,
  `number` VARCHAR(16) NOT NULL,
  `moisture` FLOAT NOT NULL,
  `garbage` FLOAT NOT NULL,
  `minerals` FLOAT NOT NULL,
  `nature` FLOAT NOT NULL,
  PRIMARY KEY (`id`, `Crop_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Consignment_OUT_Crop1_idx` (`Crop_id` ASC) VISIBLE,
  CONSTRAINT `fk_Consignment_OUT_Crop1`
    FOREIGN KEY (`Crop_id`)
    REFERENCES `bread.loc`.`Crop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
